# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: opentelemetry-instrumentation-confluent-kafka
  version: "0.57b0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_confluent_kafka-${{ version }}.tar.gz
  sha256: d28397f28684c225ba874241c804c1c87167be698d0607ab875c5cc9d0e68a95

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - python-confluent-kafka >=1.8.2,<=2.11.0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-api >=1.12,<2.dev0
    - wrapt >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - opentelemetry.instrumentation.confluent_kafka
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenTelemetry Confluent Kafka instrumentation
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-confluent-kafka
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
