# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.64b0"

package:
  name: opentelemetry-instrumentation-confluent-kafka
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/opentelemetry-instrumentation-confluent-kafka/opentelemetry_instrumentation_confluent_kafka-${{ version }}.tar.gz
  sha256: 985cea8cd00881181eb330142a67d5bc1607a60bb0eba30a888fb5260a311e76

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - opentelemetry-instrumentation==${{ version }}
    - opentelemetry-semantic-conventions==${{ version }}
    - opentelemetry-api >=1.12,<2.dev0
    - wrapt >=1.0.0,<3.0.0
    - python-confluent-kafka >=1.8.2,<=2.11.0

tests:
  - python:
      imports:
        - opentelemetry.instrumentation.confluent_kafka
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-confluent-kafka
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenTelemetry Confluent Kafka instrumentation
  description: |
    OpenTelemetry Confluent Kafka instrumentation
  repository: https://github.com/open-telemetry/opentelemetry-python-contrib

extra:
  recipe-maintainers:
    - rxm7706
